version: '3.9'

services:
  nginx_proxy:
    image: nginx:${NGINX_VERSION}
    container_name: nginx_proxy
    restart: unless-stopped
    volumes:
      - /home/${NAME_PROJECT}/nginx:/etc/nginx
      - /home/${NAME_PROJECT}/nginx/www:/data/www
      - /home/${NAME_PROJECT}/certs:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      TZ: ${TIME_ZONE}
    ports:
      - 5432:5432
    volumes:
      - /home/${NAME_PROJECT}/data:/var/lib/postgresql/data/
   
  privacyidea:
    depends_on:
      - postgres
    container_name: privacyidea
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      DB_PORT: 5432
      PROXY_ADDRESS_FORWARDING: true
    image: khalibre/privacyidea:${PRIVACYIDEA_VERSION}
    ports:
      - 8080:8080
    restart: unless-stopped
