version: '3.3'

services:
  nginx_proxy:
    image: nginx:${NGINX_VERSION}
    container_name: nginx_proxy
    restart: unless-stopped
    volumes:
      - /home/${NAME_PROJECT}/nginx:/etc/nginx
      - /home/${NAME_PROJECT}/certs:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      TZ: ${TIME_ZONE}
    ports:
      - 5432:5432
    volumes:
      - /home/${NAME_PROJECT}/data:/var/lib/postgresql/data/

  privacyidea:
    depends_on:
      - postgres
    container_name: privacyidea
    environment:
      DB_VENDOR: postgresql
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      DB_PORT: 5432
      SECRET_KEY: ${SECRET_KEY}
      PI_PEPPER: ${PI_PEPPER}
    image: esutwo/privacyidea:${PRIVACYIDEA_VERSION}
    ports:
      - 8000:8000
    restart: unless-stopped
